[build]
  base = "/"
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "20" }

[build.environment]
  NPM_VERSION = "8"
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build:prod"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"
